// Mocks generated by Mockito 5.4.4 from annotations
// in pillmate/test/map_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:google_maps_flutter/google_maps_flutter.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:pillmate/services/map.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MapService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapService extends _i1.Mock implements _i2.MapService {
  @override
  _i3.Future<_i4.LatLng?> getCurrentLocation() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [],
        ),
        returnValue: _i3.Future<_i4.LatLng?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.LatLng?>.value(),
      ) as _i3.Future<_i4.LatLng?>);

  @override
  _i3.Future<String> getDistanceFromLatLng(
    String? origins,
    String? destinations,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDistanceFromLatLng,
          [
            origins,
            destinations,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getDistanceFromLatLng,
            [
              origins,
              destinations,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getDistanceFromLatLng,
            [
              origins,
              destinations,
            ],
          ),
        )),
      ) as _i3.Future<String>);
}
