// Mocks generated by Mockito 5.4.4 from annotations
// in pillmate/test/sqlite_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pillmate/models/app_config.dart' as _i6;
import 'package:pillmate/models/daily_med.dart' as _i8;
import 'package:pillmate/models/medicine.dart' as _i7;
import 'package:pillmate/models/personal_information.dart' as _i5;
import 'package:pillmate/services/sqlite_service.dart' as _i3;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SqliteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSqliteService extends _i1.Mock implements _i3.SqliteService {
  @override
  _i4.Future<_i2.Database> initializeDB() => (super.noSuchMethod(
        Invocation.method(
          #initializeDB,
          [],
        ),
        returnValue: _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.method(
            #initializeDB,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.method(
            #initializeDB,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Database>);

  @override
  _i4.Future<int> createPersonalInfoItem(
          _i5.PersonalInformationModel? personalInformation) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPersonalInfoItem,
          [personalInformation],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> createAppConfigItem(_i6.AppConfigModel? appConfigModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAppConfigItem,
          [appConfigModel],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> createMedicineItem(_i7.MedicineModel? medicine) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMedicineItem,
          [medicine],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> createDailyMedItem(_i8.DaileyMedModel? daileyMedModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDailyMedItem,
          [daileyMedModel],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> deleteMedicineItem(String? qrcodeID) => (super.noSuchMethod(
        Invocation.method(
          #deleteMedicineItem,
          [qrcodeID],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> inactivateStatus(_i7.MedicineModel? medicine) =>
      (super.noSuchMethod(
        Invocation.method(
          #inactivateStatus,
          [medicine],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> increaseAmountTaken(
    String? qrcodeID,
    int? amountTaken,
    String? medicationSchedule,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #increaseAmountTaken,
          [
            qrcodeID,
            amountTaken,
            medicationSchedule,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> alterMedicationSchedule(
    String? qrcodeID,
    String? medicationSchedule,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alterMedicationSchedule,
          [
            qrcodeID,
            medicationSchedule,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.MedicineModel>> getMedicines() => (super.noSuchMethod(
        Invocation.method(
          #getMedicines,
          [],
        ),
        returnValue:
            _i4.Future<List<_i7.MedicineModel>>.value(<_i7.MedicineModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.MedicineModel>>.value(<_i7.MedicineModel>[]),
      ) as _i4.Future<List<_i7.MedicineModel>>);

  @override
  _i4.Future<List<_i7.MedicineModel>> getActiveMedicine() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveMedicine,
          [],
        ),
        returnValue:
            _i4.Future<List<_i7.MedicineModel>>.value(<_i7.MedicineModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.MedicineModel>>.value(<_i7.MedicineModel>[]),
      ) as _i4.Future<List<_i7.MedicineModel>>);

  @override
  _i4.Future<List<_i8.DaileyMedModel>> getDailyMedicines() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDailyMedicines,
          [],
        ),
        returnValue:
            _i4.Future<List<_i8.DaileyMedModel>>.value(<_i8.DaileyMedModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i8.DaileyMedModel>>.value(<_i8.DaileyMedModel>[]),
      ) as _i4.Future<List<_i8.DaileyMedModel>>);

  @override
  _i4.Future<void> alterDailyAmountTaken(int? amountTaken) =>
      (super.noSuchMethod(
        Invocation.method(
          #alterDailyAmountTaken,
          [amountTaken],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> alterDailyMed(int? med) => (super.noSuchMethod(
        Invocation.method(
          #alterDailyMed,
          [med],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> increaseDailyMed(int? med) => (super.noSuchMethod(
        Invocation.method(
          #increaseDailyMed,
          [med],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> decreaseDailyMed(int? med) => (super.noSuchMethod(
        Invocation.method(
          #decreaseDailyMed,
          [med],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateNotificationTime(
    int? morningHour,
    int? morningMinute,
    int? noonHour,
    int? noonMinute,
    int? eveningHour,
    int? eveningMinute,
    int? nightHour,
    int? nightMinute,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNotificationTime,
          [
            morningHour,
            morningMinute,
            noonHour,
            noonMinute,
            eveningHour,
            eveningMinute,
            nightHour,
            nightMinute,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> turnOffNotification() => (super.noSuchMethod(
        Invocation.method(
          #turnOffNotification,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> turnOnNotification() => (super.noSuchMethod(
        Invocation.method(
          #turnOnNotification,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> turnOffChangeFontSize() => (super.noSuchMethod(
        Invocation.method(
          #turnOffChangeFontSize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> turnOnChangeFontSize() => (super.noSuchMethod(
        Invocation.method(
          #turnOnChangeFontSize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> turnOffDarkMode() => (super.noSuchMethod(
        Invocation.method(
          #turnOffDarkMode,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> turnOnDarkMode() => (super.noSuchMethod(
        Invocation.method(
          #turnOnDarkMode,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> alterFontSize(int? change) => (super.noSuchMethod(
        Invocation.method(
          #alterFontSize,
          [change],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.MedicineModel>> getInactiveMedicine() =>
      (super.noSuchMethod(
        Invocation.method(
          #getInactiveMedicine,
          [],
        ),
        returnValue:
            _i4.Future<List<_i7.MedicineModel>>.value(<_i7.MedicineModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.MedicineModel>>.value(<_i7.MedicineModel>[]),
      ) as _i4.Future<List<_i7.MedicineModel>>);

  @override
  _i4.Future<bool> getEditFontSizeStatus() => (super.noSuchMethod(
        Invocation.method(
          #getEditFontSizeStatus,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> getFontSizeChange() => (super.noSuchMethod(
        Invocation.method(
          #getFontSizeChange,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<bool> getDarkModeStatus() => (super.noSuchMethod(
        Invocation.method(
          #getDarkModeStatus,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i5.PersonalInformationModel>> getPersonalInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonalInfo,
          [],
        ),
        returnValue: _i4.Future<List<_i5.PersonalInformationModel>>.value(
            <_i5.PersonalInformationModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.PersonalInformationModel>>.value(
                <_i5.PersonalInformationModel>[]),
      ) as _i4.Future<List<_i5.PersonalInformationModel>>);
}
